FROM openjdk:21-ea-1-jdk-slim

ENV JAVA_OPTS " -Xms512 -Xmx512 -Djava.security.egd=file:/dev/./urandom"

WORKDIR application

COPY ./target/kbe-rest-brewery-0.0.1-SNAPSHOT.jar ./

ENTRYPOINT ["java", "-jar", "kbe-rest-brewery-0.0.1-SNAPSHOT.jar"]